### ISSUE TITLE
Add exclusion fields to project config

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe-saml#1]
We're running into name fields in the external database being all-caps,  so then the user profiles are all-caps on the website. Could a project-level config be used to skip updating fields in `self.mergeProfile`? I'm thinking an `excludeFields` array. CC @boutell

**Comment by boutell** [comment]
I think it might be best to override `updateUser` if you want to do something unusual like saying "I trust this attribute when I am creating a user" (right? This is why you can't use the existing attributeMapping option?) "... but I don't trust it when I'm updating a user."

**Comment by boutell** [comment]
Then again, if this is a major university with whom we frequently work that we're talking about, then we're bound to have the issue a lot, so a way to distinguish fields that are trusted only at create time from fields that should override at update time might be a good idea.

**Comment by boutell** [comment]
It is worth asking if the upstream data can be fixed, or if this appears to be a school-wide policy.

**Comment by woodbrearlham** [comment]
isn't this issue been fixed?

**Comment by abea** [comment]
Yep!
